/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export class Mime {
  static parseStr(mimeStr: string): Mime | null
  toStr(): string
  static TEXT_PLAIN(): Mime
  static TEXT_HTML(): Mime
  static JSON(): Mime
  static JPG(): Mime
  static PNG(): Mime
  static isValidMime(mimeStr: string): boolean
  isText(): boolean
  isImage(): boolean
}
